// const parent=document.querySelector('.parent')
// const div=document.createElement('div')
// div.className="main"
// div.id=Math.round(Math.random()*10+1)
// div.setAttribute("title","generated by AI")
// div.style.backgroundColor="lightblue"
// div.style.padding="10px"
// // div.innerHTML="Chai Aur Code"
// const addText=document.createTextNode("chai aur code")
// div.appendChild(addText)
// document.body.appendChild(div)


// function addLang(langname){
//   const list=document.createElement('li');
//   list.innerHTML=`${langname}`
//   document.querySelector('.language').appendChild(list)
  
// }
// addLang("python")
// addLang('Golang')

// function optLang(langname){
//   const list=document.createElement('li');
//   list.appendChild(document.createTextNode(langname))
//   document.querySelector('.language').appendChild(list)
// }
// optLang('java')

// let btn=document.querySelector('.btn')
// btn.addEventListener('click',test)
// function test(){
//  btn.style.backgroundColor="red"
  
// }
let para=document.querySelector("p")
// let btnclear=document.querySelector('btnclear')
// let btn=document.querySelector('.btn')

// btn.addEventListener('click',()=>{
//   para.style.backgroundColor="yellow"
//   para.style.fontSize="24px"
// })
// btnclear.addEventListener('click',()=>{
//   para.className
// })

let addClassBtn=document.querySelector("#addClass")
let removeClassBtn=document.querySelector("#removeClass")
let toogleClassBtn=document.querySelector("#toggleClass")

addClassBtn.addEventListener('click',()=>{
  para.classList.add("activepara")
})
removeClassBtn.addEventListener('click',()=>{
  para.classList.remove("activepara")
});

toogleClassBtn.addEventListener('click',()=>{
  para.classList.toggle("activepara")
})