// const parent=document.querySelector('.parent')
// const div=document.createElement('div')
// div.className="main"
// div.id=Math.round(Math.random()*10+1)
// div.setAttribute("title","generated by AI")
// div.style.backgroundColor="lightblue"
// div.style.padding="10px"
// // div.innerHTML="Chai Aur Code"
// const addText=document.createTextNode("chai aur code")
// div.appendChild(addText)
// document.body.appendChild(div)


// function addLang(langname){
//   const list=document.createElement('li');
//   list.innerHTML=`${langname}`
//   document.querySelector('.language').appendChild(list)
  
// }
// addLang("python")
// addLang('Golang')

// function optLang(langname){
//   const list=document.createElement('li');
//   list.appendChild(document.createTextNode(langname))
//   document.querySelector('.language').appendChild(list)
// }
// optLang('java')

// let btn=document.querySelector('.btn')
// btn.addEventListener('click',test)
// function test(){
//  btn.style.backgroundColor="red"
  
// }


let btn=document.querySelector('.btn')
let body=document.body
btn.addEventListener('click',()=>{
  let randomcolorGreen=Math.round(Math.random()*255)
  let randomcolorBlue=Math.round(Math.random()*255)
  let randomcolorRed=Math.round(Math.random()*255)
  body.style.background=`rgb(${randomcolorBlue},${randomcolorGreen},${randomcolorRed})`
  })